export default [
  {
    carId: 1,
    image: 'https://asset.honda-indonesia.com/colors/6TpNmfupqEP42XgzMXjT6iLv06MPbJZUGFjoUj6e.png',
    name: 'Brio MMM',
    carType: 'Sedan',
    rating: '4',
    fuel: 'Petrol',
    hourRate: '1000',
    dayRate: '500',
    monthRate: '100',
  },
  {
    carId: 2,
    image: 'https://asset.honda-indonesia.com/colors/6TpNmfupqEP42XgzMXjT6iLv06MPbJZUGFjoUj6e.png',
    name: 'Brio MMM',
    carType: 'Sedan',
    rating: '4',
    fuel: 'Petrol',
    hourRate: '1000',
    dayRate: '500',
    monthRate: '100',
  },
  {
    carId: 3,
    image: 'https://asset.honda-indonesia.com/colors/6TpNmfupqEP42XgzMXjT6iLv06MPbJZUGFjoUj6e.png',
    name: 'Brio MMM',
    carType: 'Sedan',
    rating: '4',
    fuel: 'Petrol',
    hourRate: '1000',
    dayRate: '500',
    monthRate: '100',
  },
  {
    carId: 4,
    image: 'https://asset.honda-indonesia.com/colors/6TpNmfupqEP42XgzMXjT6iLv06MPbJZUGFjoUj6e.png',
    name: 'Brio MMM',
    carType: 'Sedan',
    rating: '4',
    fuel: 'Petrol',
    hourRate: '1000',
    dayRate: '500',
    monthRate: '100',
  },
  {
    carId: 5,
    image: 'https://asset.honda-indonesia.com/colors/6TpNmfupqEP42XgzMXjT6iLv06MPbJZUGFjoUj6e.png',
    name: 'Brio MMM',
    carType: 'Sedan',
    rating: '4',
    fuel: 'Petrol',
    hourRate: '1000',
    dayRate: '500',
    monthRate: '100',
  },
  {
    carId: 6,
    image: 'https://asset.honda-indonesia.com/colors/6TpNmfupqEP42XgzMXjT6iLv06MPbJZUGFjoUj6e.png',
    name: 'Brio MMM',
    carType: 'Sedan',
    rating: '4',
    fuel: 'Petrol',
    hourRate: '1000',
    dayRate: '500',
    monthRate: '100',
  },
  {
    carId: 7,
    image: 'https://asset.honda-indonesia.com/colors/6TpNmfupqEP42XgzMXjT6iLv06MPbJZUGFjoUj6e.png',
    name: 'Brio MMM',
    carType: 'Sedan',
    rating: '4',
    fuel: 'Petrol',
    hourRate: '1000',
    dayRate: '500',
    monthRate: '100',
  },
  {
    carId: 8,
    image: 'https://asset.honda-indonesia.com/colors/6TpNmfupqEP42XgzMXjT6iLv06MPbJZUGFjoUj6e.png',
    name: 'Brio MMM',
    carType: 'Sedan',
    rating: '4',
    fuel: 'Petrol',
    hourRate: '1000',
    dayRate: '500',
    monthRate: '100',
  },
  {
    carId: 9,
    image: 'https://asset.honda-indonesia.com/colors/6TpNmfupqEP42XgzMXjT6iLv06MPbJZUGFjoUj6e.png',
    name: 'Brio MMM',
    carType: 'Sedan',
    rating: '4',
    fuel: 'Petrol',
    hourRate: '1000',
    dayRate: '500',
    monthRate: '100',
  },
  {
    carId: 10,
    image: 'https://asset.honda-indonesia.com/colors/6TpNmfupqEP42XgzMXjT6iLv06MPbJZUGFjoUj6e.png',
    name: 'Brio MMM',
    carType: 'Sedan',
    rating: '4',
    fuel: 'Petrol',
    hourRate: '1000',
    dayRate: '500',
    monthRate: '100',
  },
  {
    carId: 11,
    image: 'https://asset.honda-indonesia.com/colors/6TpNmfupqEP42XgzMXjT6iLv06MPbJZUGFjoUj6e.png',
    name: 'Brio MMM',
    carType: 'Sedan',
    rating: '4',
    fuel: 'Petrol',
    hourRate: '1000',
    dayRate: '500',
    monthRate: '100',
  },
];
